'use strict';

const path = require('path');

/////////////////////////* DIRECTORIES */////////////////////////
const WEBPACK_TURNKEY_PROJECT_DIR =
    process.env.WEBPACK_TURNKEY_PROJECT_DIR =
    module.exports.WEBPACK_TURNKEY_PROJECT_DIR =
    process.env.WEBPACK_TURNKEY_PROJECT_DIR
        || path.resolve();

const WEBPACK_TURNKEY_ASSET_SUFFIX =
    process.env.WEBPACK_TURNKEY_ASSET_SUFFIX =
    module.exports.WEBPACK_TURNKEY_ASSET_SUFFIX =
    process.env.WEBPACK_TURNKEY_ASSET_SUFFIX
        || 'assets';

const WEBPACK_TURNKEY_ASSET_DIR =
    process.env.WEBPACK_TURNKEY_ASSET_DIR =
    module.exports.WEBPACK_TURNKEY_ASSET_DIR =
    process.env.WEBPACK_TURNKEY_ASSET_DIR
        || path.resolve(WEBPACK_TURNKEY_PROJECT_DIR, WEBPACK_TURNKEY_ASSET_SUFFIX);

const WEBPACK_TURNKEY_PAGE_SUFFIX =
    process.env.WEBPACK_TURNKEY_PAGE_SUFFIX =
    module.exports.WEBPACK_TURNKEY_PAGE_SUFFIX =
    process.env.WEBPACK_TURNKEY_PAGE_SUFFIX
        || 'pages';

const WEBPACK_TURNKEY_PAGE_DIR =
    process.env.WEBPACK_TURNKEY_PAGE_DIR =
    module.exports.WEBPACK_TURNKEY_PAGE_DIR =
    process.env.WEBPACK_TURNKEY_PAGE_DIR
        || path.resolve(WEBPACK_TURNKEY_ASSET_DIR, WEBPACK_TURNKEY_PAGE_SUFFIX);

const WEBPACK_TURNKEY_PUBLIC_SUFFIX =
    process.env.WEBPACK_TURNKEY_PUBLIC_SUFFIX =
    module.exports.WEBPACK_TURNKEY_PUBLIC_SUFFIX =
    process.env.WEBPACK_TURNKEY_PUBLIC_SUFFIX || 'public';

const WEBPACK_TURNKEY_PUBLIC_DIR =
    process.env.WEBPACK_TURNKEY_PUBLIC_DIR =
    module.exports.WEBPACK_TURNKEY_PUBLIC_DIR =
    process.env.WEBPACK_TURNKEY_PUBLIC_DIR
        || path.resolve(WEBPACK_TURNKEY_PROJECT_DIR, WEBPACK_TURNKEY_PUBLIC_SUFFIX);

const WEBPACK_TURNKEY_OUTPUT_SUFFIX =
    process.env.WEBPACK_TURNKEY_OUTPUT_SUFFIX =
    module.exports.WEBPACK_TURNKEY_OUTPUT_SUFFIX =
    process.env.WEBPACK_TURNKEY_OUTPUT_SUFFIX
        || 'js';

const WEBPACK_TURNKEY_OUTPUT_DIR =
    process.env.WEBPACK_TURNKEY_OUTPUT_DIR =
    module.exports.WEBPACK_TURNKEY_OUTPUT_DIR =
    process.env.WEBPACK_TURNKEY_OUTPUT_DIR
        || path.resolve(WEBPACK_TURNKEY_PUBLIC_DIR, WEBPACK_TURNKEY_OUTPUT_SUFFIX);